[tool.poetry]
name = "tvarkdarys"
version = "0.1.0"
description = ""
authors = ["ToxicM8"]

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "^20.0"
telegram = "^0.0.1"
flask = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"